# Generated by Django 4.2.7 on 2024-06-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_cartitem_cartproduct_remove_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
